### PR TITLE
modernize-use-nodiscard

### PR DESCRIPTION
**Pull request by jfmherokiller**

### CODE REVIEW

**Comment by Ryan-rsm-McKenzie** [comment]
Can you run the formatter?

**Comment by jfm535** [comment]
ill remake this commit using latest master

**Comment by jfm535** [comment]
sure running it now

**Comment by jfm535** [comment]
rebased onto latest master

**Comment by jfm535** [comment]
I removed my own formatting commit as to not overwrite yours

**Comment by Ryan-rsm-McKenzie** [comment]
you need to rebase

**Pull request merged**
