### PR TITLE
Add "ResetAI" member function to Actor class. (Rewrited)

### PR DESCRIPTION
**Pull request by max-su-2019**
Add "ResetAI" member function to Actor class.

### CODE REVIEW

**Comment by Ryan-rsm-McKenzie** [comment]
This function already exists as [`EvaluatePackage`](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/master/include/RE/FormComponents/TESForm/TESObjectREFR/Actor/Actor.h#L498)

**Comment by max-su-2019** [comment]
> This function already exists as [`EvaluatePackage`](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/master/include/RE/FormComponents/TESForm/TESObjectREFR/Actor/Actor.h#L498)

Well, I just found out they are both are the same addresss.

But the different is that the argument value they passed is different, which make a different effect. I will do some little adjustment for that.

**Comment by Ryan-rsm-McKenzie** [comment]
If you need to reset the ai, you can set this flag
https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/d626e8a4935e7b46b42d983e47a1612fc5bacceb/include/RE/FormComponents/TESForm/TESObjectREFR/Actor/Actor.h#L176

**Comment by max-su-2019** [comment]
Okay, that's fine. Then I will revert this pull request.

**Pull request closed without merging**
